import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Adiel Tapari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Web Site Adiel </h1>
    </div>
  );
}
